# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowF.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.width = QtWidgets.QApplication.desktop().screenGeometry().width()
        self.height = QtWidgets.QApplication.desktop().screenGeometry().height()
        MainWindow.resize(self.width/1.5, self.height/1.2)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.splitter1 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.gridLayout3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout3.setObjectName("gridLayout3")
        self.gridLayout3.addWidget(self.splitter1,0,0,3,3)

        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout3.addWidget(self.line_3,3,0,1,3)
        self.widget = QtWidgets.QWidget(self.centralwidget)

        self.widget.setMaximumSize(350,30)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout3.addWidget(self.widget,4,2,1,1)

        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setMinimumHeight(25)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumHeight(25)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setMinimumHeight(25)
        self.horizontalLayout_2.addWidget(self.pushButton_5)


        self.widget1 = QtWidgets.QWidget(self.splitter1)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 20, 361, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout1.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setText("线缆连接测量")
        self.horizontalLayout1.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setText("天线连接测量")
        self.horizontalLayout1.addWidget(self.radioButton_2)
        self.verticalLayout.addWidget(self.horizontalLayoutWidget)

        self.pyqtgraph1 = pg.GraphicsLayoutWidget(self.widget1)
        self.pyqtgraph1.setObjectName("pyqtgraph1")
        self.pyqtgraph1.setBackground('#F8F8FF')
        self.verticalLayout.addWidget(self.pyqtgraph1)
        self.progressBar = QtWidgets.QProgressBar(self.widget1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setMaximumSize(200,30)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setMaximumSize(200,30)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_4.setMaximumSize(200,30)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_3.setMaximumSize(200,30)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setEnabled(False)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)

        self.widget2 = QtWidgets.QWidget(self.splitter1)
        self.widget2.setMaximumSize(QtCore.QSize(400,2000))
        self.widget2.setMinimumSize(QtCore.QSize(300, 300))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formGroupBox = QtWidgets.QGroupBox(self.widget2)
        self.formGroupBox.setObjectName("formGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_11 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_11.setObjectName("Label_11")
        self.gridLayout.addWidget(self.Label_11, 0, 0, 1, 1)
        self.LineEdit_11 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_11.setObjectName("LineEdit_11")
        self.gridLayout.addWidget(self.LineEdit_11, 0, 2, 1, 1)
        self.Label_12 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_12.setObjectName("Label_12")
        self.gridLayout.addWidget(self.Label_12, 1, 0, 1, 1)
        self.Label_13 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_13.setObjectName("Label_12")
        self.gridLayout.addWidget(self.Label_13, 1, 3, 1, 1)
        self.LineEdit_12 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_12.setObjectName("LineEdit_12")
        self.gridLayout.addWidget(self.LineEdit_12, 1, 2, 1, 1)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout.addWidget(self.LineEdit_2, 3, 2, 1, 1)
        self.Label_7 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_7.setObjectName("Label_7")
        self.gridLayout.addWidget(self.Label_7, 8, 0, 1, 1)
        self.LineEdit_10 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_10.setObjectName("LineEdit_10")
        self.gridLayout.addWidget(self.LineEdit_10, 12, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.formGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 3, 1, 1)
        self.LineEdit_6 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.gridLayout.addWidget(self.LineEdit_6, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.formGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 3, 1, 1)
        self.Label_9 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_9.setObjectName("Label_9")
        self.gridLayout.addWidget(self.Label_9, 11, 0, 1, 1)
        self.LineEdit_8 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.gridLayout.addWidget(self.LineEdit_8, 9, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 3, 1, 1)
        self.LineEdit_7 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.gridLayout.addWidget(self.LineEdit_7, 8, 2, 1, 1)
        self.LineEdit_9 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_9.setObjectName("LineEdit_9")
        self.gridLayout.addWidget(self.LineEdit_9, 11, 2, 1, 1)
        self.Label_8 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_8.setObjectName("Label_8")
        self.gridLayout.addWidget(self.Label_8, 9, 0, 1, 1)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.gridLayout.addWidget(self.LineEdit_4, 5, 2, 1, 1)
        self.Label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_4.setObjectName("Label_4")
        self.gridLayout.addWidget(self.Label_4, 5, 0, 1, 1)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout.addWidget(self.LineEdit_3, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 3, 1, 1)
        self.Label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 3, 0, 1, 1)
        self.Label_10 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_10.setObjectName("Label_10")
        self.gridLayout.addWidget(self.Label_10, 12, 0, 1, 1)
        self.LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout.addWidget(self.LineEdit, 2, 2, 1, 1)
        self.Label_6 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_6.setObjectName("Label_6")
        self.gridLayout.addWidget(self.Label_6, 7, 0, 1, 1)
        self.Label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout.addWidget(self.Label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 3, 1, 1)
        self.Label = QtWidgets.QLabel(self.formGroupBox)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.formGroupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setMaximumWidth(180)
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setMaximumWidth(180)
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setMaximumWidth(180)
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        self.action3_2.setObjectName("action3_2")
        self.action4_2 = QtWidgets.QAction(MainWindow)
        self.action4_2.setObjectName("action4_2")
        self.action5_2 = QtWidgets.QAction(MainWindow)
        self.action5_2.setObjectName("action5_2")
        self.actionconnect = QtWidgets.QAction(MainWindow)
        self.actionconnect.setObjectName("actionconnect")
        self.actiondisconnect = QtWidgets.QAction(MainWindow)
        self.actiondisconnect.setObjectName("actiondisconnect")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setCheckable(False)
        self.actionopen.setObjectName("actionopen")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action1_3 = QtWidgets.QAction(MainWindow)
        self.action1_3.setObjectName("action1_3")
        self.action1_4 = QtWidgets.QAction(MainWindow)
        self.action1_4.setObjectName("action1_4")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.actionopen)
        self.menu.addSeparator()
        self.menu.addAction(self.action1)
        self.menu.addAction(self.action2)
        self.menu.addAction(self.action)
        self.menu.addAction(self.action3)
        self.menu.addSeparator()
        self.menu.addAction(self.action4)
        self.menu.addSeparator()
        self.menu.addAction(self.action5)
        self.menu_3.addAction(self.actionhelp)
        self.menu_4.addAction(self.actionconnect)
        self.menu_4.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LineEdit_2, self.LineEdit_3)
        MainWindow.setTabOrder(self.LineEdit_3, self.LineEdit_4)
        MainWindow.setTabOrder(self.LineEdit_4, self.LineEdit_6)
        MainWindow.setTabOrder(self.LineEdit_6, self.LineEdit_7)
        MainWindow.setTabOrder(self.LineEdit_7, self.LineEdit_8)
        MainWindow.setTabOrder(self.LineEdit_8, self.LineEdit_9)
        MainWindow.setTabOrder(self.LineEdit_9, self.LineEdit_10)
        MainWindow.setTabOrder(self.LineEdit_10, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "场地系统衰减测试"))
        self.pushButton_8.setText(_translate("MainWindow", "读取结果"))
        self.pushButton_11.setText(_translate("MainWindow", "计算最终路径损耗"))
        self.pushButton_5.setText(_translate("MainWindow", "保存结果"))
        self.Label_11.setText(_translate("MainWindow", "模式"))
        self.Label_12.setText(_translate("MainWindow", "天线增益"))
        self.Label_13.setText(_translate("MainWindow", "dBm"))
        # self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        self.pushButton_2.setText(_translate("MainWindow", "暂停"))
        self.pushButton_4.setText(_translate("MainWindow", "继续"))
        self.pushButton_3.setText(_translate("MainWindow", "结束"))
        self.Label_7.setText(_translate("MainWindow", "输出功率:"))
        self.label_7.setText(_translate("MainWindow", "ns"))
        self.label_6.setText(_translate("MainWindow", "dB"))
        self.label_3.setText(_translate("MainWindow", "kHz"))
        self.Label_9.setText(_translate("MainWindow", "扫描点数:"))
        self.label_2.setText(_translate("MainWindow", "MHz"))
        self.Label_8.setText(_translate("MainWindow", "电延时:"))
        self.Label_4.setText(_translate("MainWindow", "中频带宽:"))
        self.label_5.setText(_translate("MainWindow", "次"))
        self.Label_2.setText(_translate("MainWindow", "起始频率:"))
        self.Label_10.setText(_translate("MainWindow", "文件名:"))
        self.Label_6.setText(_translate("MainWindow", "平均次数:"))
        self.Label_3.setText(_translate("MainWindow", "终止频率:"))
        self.label.setText(_translate("MainWindow", "MHz"))
        self.Label.setText(_translate("MainWindow", "地址:"))
        self.pushButton_6.setText(_translate("MainWindow", "保存设置"))
        self.pushButton_7.setText(_translate("MainWindow", "读取设置"))
        self.pushButton_9.setText(_translate("MainWindow", "测试连接"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.menu_4.setTitle(_translate("MainWindow", "设置"))
        self.action1.setText(_translate("MainWindow", "开始"))
        self.action2.setText(_translate("MainWindow", "暂停"))
        self.action3.setText(_translate("MainWindow", "结束"))
        self.action4.setText(_translate("MainWindow", "保存测量结果"))
        self.action5.setText(_translate("MainWindow", "退出"))
        self.action1_2.setText(_translate("MainWindow", "1"))
        self.action2_2.setText(_translate("MainWindow", "2"))
        self.action3_2.setText(_translate("MainWindow", "3"))
        self.action4_2.setText(_translate("MainWindow", "4"))
        self.action5_2.setText(_translate("MainWindow", "5"))
        self.actionconnect.setText(_translate("MainWindow", "连接设置"))
        self.actiondisconnect.setText(_translate("MainWindow", "断开连接"))
        self.actionhelp.setText(_translate("MainWindow", "帮助信息"))
        self.actionopen.setText(_translate("MainWindow", "打开文件"))
        self.action.setText(_translate("MainWindow", "继续"))
        self.action1_3.setText(_translate("MainWindow", "1"))
        self.action1_4.setText(_translate("MainWindow", "1"))
        self.action_3.setText(_translate("MainWindow", "保存设置"))
