# # -*- coding: utf-8 -*-
#
# # Form implementation generated from reading ui file 'MainWindowF.ui'
# #
# # Created by: PyQt5 UI code generator 5.13.0
# #
# # WARNING! All changes made in this file will be lost!
#
#
# from PyQt5 import QtCore, QtGui, QtWidgets
# import pyqtgraph as pg
#
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         self.width = QtWidgets.QApplication.desktop().screenGeometry().width()
#         self.height = QtWidgets.QApplication.desktop().screenGeometry().height()
#         MainWindow.resize(self.width/1.5, self.height/1.2)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#
#         self.splitter1 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
#         self.gridLayout3 = QtWidgets.QGridLayout(self.centralwidget)
#         self.gridLayout3.setObjectName("gridLayout3")
#         self.gridLayout3.addWidget(self.splitter1,0,0,3,3)
#
#         self.line_3 = QtWidgets.QFrame(self.centralwidget)
#         self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_3.setObjectName("line_3")
#         self.gridLayout3.addWidget(self.line_3,3,0,1,3)
#         self.widget = QtWidgets.QWidget(self.centralwidget)
#
#         self.widget.setMaximumSize(350,30)
#         self.widget.setObjectName("widget")
#         self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
#         self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout_2.setObjectName("horizontalLayout_2")
#         self.gridLayout3.addWidget(self.widget,4,2,1,1)
#
#         self.pushButton_11 = QtWidgets.QPushButton(self.widget)
#         self.pushButton_11.setMinimumHeight(25)
#         self.pushButton_11.setObjectName("pushButton_11")
#         self.horizontalLayout_2.addWidget(self.pushButton_11)
#         self.pushButton_8 = QtWidgets.QPushButton(self.widget)
#         self.pushButton_8.setMinimumHeight(25)
#         self.pushButton_8.setObjectName("pushButton_8")
#         self.horizontalLayout_2.addWidget(self.pushButton_8)
#         self.pushButton_5 = QtWidgets.QPushButton(self.widget)
#         self.pushButton_5.setObjectName("pushButton_5")
#         self.pushButton_5.setMinimumHeight(25)
#         self.horizontalLayout_2.addWidget(self.pushButton_5)
#
#
#         self.widget1 = QtWidgets.QWidget(self.splitter1)
#         self.widget1.setObjectName("widget1")
#         self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
#         self.horizontalLayout_4.setGeometry(QtCore.QRect(10, 11, 800, 671))
#         self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout_4.setObjectName("horizontalLayout_4")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget1)
#         self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 20, 361, 61))
#         self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
#         self.horizontalLayout1 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
#         self.horizontalLayout1.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout1.setObjectName("horizontalLayout")
#         self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
#         self.radioButton.setObjectName("radioButton")
#         self.radioButton.setText("线缆连接测量")
#         self.horizontalLayout1.addWidget(self.radioButton)
#         self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
#         self.radioButton_2.setObjectName("radioButton_2")
#         self.radioButton_2.setText("天线连接测量")
#         self.horizontalLayout1.addWidget(self.radioButton_2)
#         self.verticalLayout.addWidget(self.horizontalLayoutWidget)
#
#         self.pyqtgraph1 = pg.GraphicsLayoutWidget(self.widget1)
#         self.pyqtgraph1.setObjectName("pyqtgraph1")
#         self.pyqtgraph1.setBackground('#F8F8FF')
#         self.verticalLayout.addWidget(self.pyqtgraph1)
#         self.progressBar = QtWidgets.QProgressBar(self.widget1)
#         self.progressBar.setProperty("value", 24)
#         self.progressBar.setObjectName("progressBar")
#         self.verticalLayout.addWidget(self.progressBar)
#         self.line_2 = QtWidgets.QFrame(self.widget1)
#         self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_2.setObjectName("line_2")
#         self.verticalLayout.addWidget(self.line_2)
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.pushButton = QtWidgets.QPushButton(self.widget1)
#         self.pushButton.setMaximumSize(200,30)
#         self.pushButton.setObjectName("pushButton")
#         self.horizontalLayout.addWidget(self.pushButton)
#         self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_2.setMaximumSize(200,30)
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.horizontalLayout.addWidget(self.pushButton_2)
#         self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_4.setMaximumSize(200,30)
#         self.pushButton_4.setObjectName("pushButton_4")
#         self.horizontalLayout.addWidget(self.pushButton_4)
#         self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_3.setMaximumSize(200,30)
#         self.pushButton_3.setObjectName("pushButton_3")
#         self.horizontalLayout.addWidget(self.pushButton_3)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.horizontalLayout_4.addLayout(self.verticalLayout)
#         self.line = QtWidgets.QFrame(self.widget1)
#         self.line.setEnabled(False)
#         self.line.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line.setObjectName("line")
#         self.horizontalLayout_4.addWidget(self.line)
#
#         self.widget2 = QtWidgets.QWidget(self.splitter1)
#         self.widget2.setMaximumSize(QtCore.QSize(400,2000))
#         self.widget2.setMinimumSize(QtCore.QSize(300, 300))
#         self.widget2.setObjectName("widget2")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
#         self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.formGroupBox = QtWidgets.QGroupBox(self.widget2)
#         self.formGroupBox.setObjectName("formGroupBox")
#         self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
#         self.gridLayout.setObjectName("gridLayout")
#         self.Label_11 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_11.setObjectName("Label_11")
#         self.gridLayout.addWidget(self.Label_11, 0, 0, 1, 1)
#         self.LineEdit_11 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_11.setObjectName("LineEdit_11")
#         self.gridLayout.addWidget(self.LineEdit_11, 0, 2, 1, 1)
#         self.Label_12 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_12.setObjectName("Label_12")
#         self.gridLayout.addWidget(self.Label_12, 1, 0, 1, 1)
#         self.Label_13 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_13.setObjectName("Label_12")
#         self.gridLayout.addWidget(self.Label_13, 1, 3, 1, 1)
#         self.LineEdit_12 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_12.setObjectName("LineEdit_12")
#         self.gridLayout.addWidget(self.LineEdit_12, 1, 2, 1, 1)
#         self.LineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_2.setObjectName("LineEdit_2")
#         self.gridLayout.addWidget(self.LineEdit_2, 3, 2, 1, 1)
#         self.Label_7 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_7.setObjectName("Label_7")
#         self.gridLayout.addWidget(self.Label_7, 8, 0, 1, 1)
#         self.LineEdit_10 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_10.setObjectName("LineEdit_10")
#         self.gridLayout.addWidget(self.LineEdit_10, 12, 2, 1, 1)
#         self.label_7 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_7.setObjectName("label_7")
#         self.gridLayout.addWidget(self.label_7, 9, 3, 1, 1)
#         self.LineEdit_6 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_6.setObjectName("LineEdit_6")
#         self.gridLayout.addWidget(self.LineEdit_6, 7, 2, 1, 1)
#         self.label_6 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_6.setObjectName("label_6")
#         self.gridLayout.addWidget(self.label_6, 8, 3, 1, 1)
#         self.label_3 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_3.setObjectName("label_3")
#         self.gridLayout.addWidget(self.label_3, 5, 3, 1, 1)
#         self.Label_9 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_9.setObjectName("Label_9")
#         self.gridLayout.addWidget(self.Label_9, 11, 0, 1, 1)
#         self.LineEdit_8 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_8.setObjectName("LineEdit_8")
#         self.gridLayout.addWidget(self.LineEdit_8, 9, 2, 1, 1)
#         self.label_2 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_2.setObjectName("label_2")
#         self.gridLayout.addWidget(self.label_2, 3, 3, 1, 1)
#         self.LineEdit_7 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_7.setObjectName("LineEdit_7")
#         self.gridLayout.addWidget(self.LineEdit_7, 8, 2, 1, 1)
#         self.LineEdit_9 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_9.setObjectName("LineEdit_9")
#         self.gridLayout.addWidget(self.LineEdit_9, 11, 2, 1, 1)
#         self.Label_8 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_8.setObjectName("Label_8")
#         self.gridLayout.addWidget(self.Label_8, 9, 0, 1, 1)
#         self.LineEdit_4 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_4.setObjectName("LineEdit_4")
#         self.gridLayout.addWidget(self.LineEdit_4, 5, 2, 1, 1)
#         self.Label_4 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_4.setObjectName("Label_4")
#         self.gridLayout.addWidget(self.Label_4, 5, 0, 1, 1)
#         self.LineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_3.setObjectName("LineEdit_3")
#         self.gridLayout.addWidget(self.LineEdit_3, 4, 2, 1, 1)
#         self.label_5 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_5.setObjectName("label_5")
#         self.gridLayout.addWidget(self.label_5, 7, 3, 1, 1)
#         self.Label_2 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_2.setObjectName("Label_2")
#         self.gridLayout.addWidget(self.Label_2, 3, 0, 1, 1)
#         self.Label_10 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_10.setObjectName("Label_10")
#         self.gridLayout.addWidget(self.Label_10, 12, 0, 1, 1)
#         self.LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit.setObjectName("LineEdit")
#         self.gridLayout.addWidget(self.LineEdit, 2, 2, 1, 1)
#         self.Label_6 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_6.setObjectName("Label_6")
#         self.gridLayout.addWidget(self.Label_6, 7, 0, 1, 1)
#         self.Label_3 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_3.setObjectName("Label_3")
#         self.gridLayout.addWidget(self.Label_3, 4, 0, 1, 1)
#         self.label = QtWidgets.QLabel(self.formGroupBox)
#         self.label.setObjectName("label")
#         self.gridLayout.addWidget(self.label, 4, 3, 1, 1)
#         self.Label = QtWidgets.QLabel(self.formGroupBox)
#         self.Label.setObjectName("Label")
#         self.gridLayout.addWidget(self.Label, 2, 0, 1, 1)
#         self.verticalLayout_2.addWidget(self.formGroupBox)
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
#         self.horizontalLayout_3.setObjectName("horizontalLayout_3")
#         self.pushButton_6 = QtWidgets.QPushButton(self.widget2)
#         self.pushButton_6.setObjectName("pushButton_6")
#         self.pushButton_6.setMaximumWidth(180)
#         self.horizontalLayout_3.addWidget(self.pushButton_6)
#         self.pushButton_7 = QtWidgets.QPushButton(self.widget2)
#         self.pushButton_7.setObjectName("pushButton_7")
#         self.pushButton_7.setMaximumWidth(180)
#         self.horizontalLayout_3.addWidget(self.pushButton_7)
#         self.pushButton_9 = QtWidgets.QPushButton(self.widget2)
#         self.pushButton_9.setObjectName("pushButton_9")
#         self.pushButton_9.setMaximumWidth(180)
#         self.horizontalLayout_3.addWidget(self.pushButton_9)
#         self.verticalLayout_2.addLayout(self.horizontalLayout_3)
#
#
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 23))
#         self.menubar.setObjectName("menubar")
#         self.menu = QtWidgets.QMenu(self.menubar)
#         self.menu.setObjectName("menu")
#         self.menu_3 = QtWidgets.QMenu(self.menubar)
#         self.menu_3.setObjectName("menu_3")
#         self.menu_4 = QtWidgets.QMenu(self.menubar)
#         self.menu_4.setObjectName("menu_4")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#         self.action1 = QtWidgets.QAction(MainWindow)
#         self.action1.setObjectName("action1")
#         self.action2 = QtWidgets.QAction(MainWindow)
#         self.action2.setObjectName("action2")
#         self.action3 = QtWidgets.QAction(MainWindow)
#         self.action3.setObjectName("action3")
#         self.action4 = QtWidgets.QAction(MainWindow)
#         self.action4.setObjectName("action4")
#         self.action5 = QtWidgets.QAction(MainWindow)
#         self.action5.setObjectName("action5")
#         self.action1_2 = QtWidgets.QAction(MainWindow)
#         self.action1_2.setObjectName("action1_2")
#         self.action2_2 = QtWidgets.QAction(MainWindow)
#         self.action2_2.setObjectName("action2_2")
#         self.action3_2 = QtWidgets.QAction(MainWindow)
#         self.action3_2.setObjectName("action3_2")
#         self.action4_2 = QtWidgets.QAction(MainWindow)
#         self.action4_2.setObjectName("action4_2")
#         self.action5_2 = QtWidgets.QAction(MainWindow)
#         self.action5_2.setObjectName("action5_2")
#         self.actionconnect = QtWidgets.QAction(MainWindow)
#         self.actionconnect.setObjectName("actionconnect")
#         self.actiondisconnect = QtWidgets.QAction(MainWindow)
#         self.actiondisconnect.setObjectName("actiondisconnect")
#         self.actionhelp = QtWidgets.QAction(MainWindow)
#         self.actionhelp.setObjectName("actionhelp")
#         self.actionopen = QtWidgets.QAction(MainWindow)
#         self.actionopen.setCheckable(False)
#         self.actionopen.setObjectName("actionopen")
#         self.action = QtWidgets.QAction(MainWindow)
#         self.action.setObjectName("action")
#         self.action1_3 = QtWidgets.QAction(MainWindow)
#         self.action1_3.setObjectName("action1_3")
#         self.action1_4 = QtWidgets.QAction(MainWindow)
#         self.action1_4.setObjectName("action1_4")
#         self.action_3 = QtWidgets.QAction(MainWindow)
#         self.action_3.setObjectName("action_3")
#         self.menu.addAction(self.actionopen)
#         self.menu.addSeparator()
#         self.menu.addAction(self.action1)
#         self.menu.addAction(self.action2)
#         self.menu.addAction(self.action)
#         self.menu.addAction(self.action3)
#         self.menu.addSeparator()
#         self.menu.addAction(self.action4)
#         self.menu.addSeparator()
#         self.menu.addAction(self.action5)
#         self.menu_3.addAction(self.actionhelp)
#         self.menu_4.addAction(self.actionconnect)
#         self.menu_4.addAction(self.action_3)
#         self.menubar.addAction(self.menu.menuAction())
#         self.menubar.addAction(self.menu_4.menuAction())
#         self.menubar.addAction(self.menu_3.menuAction())
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#         MainWindow.setTabOrder(self.LineEdit_2, self.LineEdit_3)
#         MainWindow.setTabOrder(self.LineEdit_3, self.LineEdit_4)
#         MainWindow.setTabOrder(self.LineEdit_4, self.LineEdit_6)
#         MainWindow.setTabOrder(self.LineEdit_6, self.LineEdit_7)
#         MainWindow.setTabOrder(self.LineEdit_7, self.LineEdit_8)
#         MainWindow.setTabOrder(self.LineEdit_8, self.LineEdit_9)
#         MainWindow.setTabOrder(self.LineEdit_9, self.LineEdit_10)
#         MainWindow.setTabOrder(self.LineEdit_10, self.pushButton_6)
#         MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
#         MainWindow.setTabOrder(self.pushButton_7, self.pushButton)
#         MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
#         MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "归一化场地衰减测试"))
#         self.pushButton_8.setText(_translate("MainWindow", "读取结果"))
#         self.pushButton_11.setText(_translate("MainWindow", "计算最终NSA"))
#         self.pushButton_5.setText(_translate("MainWindow", "保存结果"))
#         self.Label_11.setText(_translate("MainWindow", "模式"))
#         self.Label_12.setText(_translate("MainWindow", "天线增益"))
#         self.Label_13.setText(_translate("MainWindow", "dBm"))
#         # self.label_8.setText(_translate("MainWindow", "TextLabel"))
#         self.pushButton.setText(_translate("MainWindow", "开始"))
#         self.pushButton_2.setText(_translate("MainWindow", "暂停"))
#         self.pushButton_4.setText(_translate("MainWindow", "继续"))
#         self.pushButton_3.setText(_translate("MainWindow", "结束"))
#         self.Label_7.setText(_translate("MainWindow", "输出功率:"))
#         self.label_7.setText(_translate("MainWindow", "ns"))
#         self.label_6.setText(_translate("MainWindow", "dB"))
#         self.label_3.setText(_translate("MainWindow", "kHz"))
#         self.Label_9.setText(_translate("MainWindow", "扫描点数:"))
#         self.label_2.setText(_translate("MainWindow", "MHz"))
#         self.Label_8.setText(_translate("MainWindow", "电延时:"))
#         self.Label_4.setText(_translate("MainWindow", "中频带宽:"))
#         self.label_5.setText(_translate("MainWindow", "次"))
#         self.Label_2.setText(_translate("MainWindow", "起始频率:"))
#         self.Label_10.setText(_translate("MainWindow", "文件名:"))
#         self.Label_6.setText(_translate("MainWindow", "平均次数:"))
#         self.Label_3.setText(_translate("MainWindow", "终止频率:"))
#         self.label.setText(_translate("MainWindow", "MHz"))
#         self.Label.setText(_translate("MainWindow", "地址:"))
#         self.pushButton_6.setText(_translate("MainWindow", "保存设置"))
#         self.pushButton_7.setText(_translate("MainWindow", "读取设置"))
#         self.pushButton_9.setText(_translate("MainWindow", "测试连接"))
#         self.menu.setTitle(_translate("MainWindow", "开始"))
#         self.menu_3.setTitle(_translate("MainWindow", "帮助"))
#         self.menu_4.setTitle(_translate("MainWindow", "设置"))
#         self.action1.setText(_translate("MainWindow", "开始"))
#         self.action2.setText(_translate("MainWindow", "暂停"))
#         self.action3.setText(_translate("MainWindow", "结束"))
#         self.action4.setText(_translate("MainWindow", "保存测量结果"))
#         self.action5.setText(_translate("MainWindow", "退出"))
#         self.action1_2.setText(_translate("MainWindow", "1"))
#         self.action2_2.setText(_translate("MainWindow", "2"))
#         self.action3_2.setText(_translate("MainWindow", "3"))
#         self.action4_2.setText(_translate("MainWindow", "4"))
#         self.action5_2.setText(_translate("MainWindow", "5"))
#         self.actionconnect.setText(_translate("MainWindow", "连接设置"))
#         self.actiondisconnect.setText(_translate("MainWindow", "断开连接"))
#         self.actionhelp.setText(_translate("MainWindow", "帮助信息"))
#         self.actionopen.setText(_translate("MainWindow", "打开文件"))
#         self.action.setText(_translate("MainWindow", "继续"))
#         self.action1_3.setText(_translate("MainWindow", "1"))
#         self.action1_4.setText(_translate("MainWindow", "1"))
#         self.action_3.setText(_translate("MainWindow", "保存设置"))


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowF.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

#
# from PyQt5 import QtCore, QtGui, QtWidgets
# import pyqtgraph as pg
#
#
# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         self.width = QtWidgets.QApplication.desktop().screenGeometry().width()
#         self.height = QtWidgets.QApplication.desktop().screenGeometry().height()
#         MainWindow.resize(self.width / 1.5, self.height / 1.1)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName("centralwidget")
#
#         self.splitter1 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
#         self.gridLayout3 = QtWidgets.QGridLayout(self.centralwidget)
#         self.gridLayout3.setObjectName("gridLayout3")
#         self.gridLayout3.addWidget(self.splitter1, 0, 0, 3, 3)
#
#         self.line_3 = QtWidgets.QFrame(self.centralwidget)
#         self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_3.setObjectName("line_3")
#         self.gridLayout3.addWidget(self.line_3, 3, 0, 1, 3)
#
#         self.ww = QtWidgets.QWidget(self.centralwidget)
#         self.gridLayout3.addWidget(self.ww, 4, 0, 1, 1)
#         self.h1 = QtWidgets.QHBoxLayout(self.ww)
#
#         self.lab1 = QtWidgets.QLabel()
#         jpg5 = QtGui.QPixmap('e:/bishe/img/cha.jpg').scaled(48, 48)
#         self.lab1.setPixmap(jpg5)
#         self.h1.addWidget(self.lab1)
#         self.lab2 = QtWidgets.QLabel()
#         self.lab2.setText('检测到未连接')
#         self.lab2.setStyleSheet("QLabel{color:rgb(255,0,0)}")
#         self.h1.addWidget(self.lab2)
#         self.pbtn1 = QtWidgets.QPushButton()
#         self.pbtn1.setMinimumWidth(80)
#         self.pbtn1.setMinimumHeight(25)
#         self.pbtn1.setText('重新连接')
#         self.h1.addWidget(self.pbtn1)
#
#
#
#         self.widget = QtWidgets.QWidget(self.centralwidget)
#         self.widget.setMaximumSize(350, 50)
#         self.widget.setObjectName("widget")
#         self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
#         self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout_2.setObjectName("horizontalLayout_2")
#         self.gridLayout3.addWidget(self.widget, 4, 2, 1, 1)
#         self.pushButton_11 = QtWidgets.QPushButton(self.widget)
#         self.pushButton_11.setMinimumHeight(25)
#         self.pushButton_11.setObjectName("pushButton_11")
#         self.horizontalLayout_2.addWidget(self.pushButton_11)
#         self.pushButton_8 = QtWidgets.QPushButton(self.widget)
#         self.pushButton_8.setMinimumHeight(25)
#         self.pushButton_8.setObjectName("pushButton_8")
#         self.horizontalLayout_2.addWidget(self.pushButton_8)
#         self.pushButton_5 = QtWidgets.QPushButton(self.widget)
#         self.pushButton_5.setObjectName("pushButton_5")
#         self.pushButton_5.setMinimumHeight(25)
#         self.horizontalLayout_2.addWidget(self.pushButton_5)
#
#         # 第一步
#         self.widget3 = QtWidgets.QWidget(self.splitter1)
#         self.widget3.setObjectName("widget3")
#         self.widget3.resize(int(self.width / 1.6), int(self.height / 1.5))
#         self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
#         self.horizontalLayout_5.setGeometry(QtCore.QRect(10, 11, 800, 671))
#         self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout_5.setObjectName("horizontalLayout_5")
#         self.gridLayout10 = QtWidgets.QGridLayout()
#         self.qtext = QtWidgets.QTextEdit()
#         self.qtext.setText('''第一步，进行校准，见章节4.1.4.
# 第二步，将矢网的port1和Tx电缆连接，将矢网的port2端口和Rx电缆连接。将2根线缆直接相连，
# 测出30-1000MHz的矢网的数值。
# 第三步，测量30-200MHz水平极化的值。将1个双锥天线，水平放置在1m高的台上，连接到Tx电缆。
# 在3m外静区中心放置第2个双锥天线，放置在1m的高台上，保证2个天线正对。读取矢网的数值。
# 随后再调整第2个双锥天线的高度，使得矢网的数值最大。记录下数值。每隔5MHz进行一次测量。
# 第四步，改变第2个天线在静区内的位置。将其分别放在中心的左、前、右的63厘米远的位置。
# 同时调整第一个天线的位置保证其距离3m。随后按照第三步进行实验。
# 第五步，将第一个天线的高度调整为2m。然后再次重复上边的第三步和第四步。
# 第五步，将天线变为垂直极化，再次重复上边的第三步和第四步和第五步。
# 第六步，将双锥天线换为对数周期天线，重复上边的第三步、第四步、第五步和第六步测量
# 300-1000MHz的结果，频率的步进是10MHz。
# 第七步，将上边测得的结果通过软件自动换算成与标准值的偏差dB。
#
# ''')
#         self.qtext.setReadOnly(True)
#         # self.qtext.setEnabled(False)
#         self.qtext.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
#         self.gridLayout10.addWidget(self.qtext, 0, 0, 1, 4)
#         self.horizontalLayout_5.addLayout(self.gridLayout10)
#         self.label_10 = QtWidgets.QLabel()
#         self.gridLayout10.addWidget(self.label_10, 1, 0, 1, 4)
#         jpg = QtGui.QPixmap('h:/bishe/img/nsa.jpg').scaled(700, 400)
#         self.label_10.setPixmap(jpg)
#         self.pushButton_12 = QtWidgets.QPushButton(self.widget3)
#         self.pushButton_12.setText('开始测量')
#         self.gridLayout10.addWidget(self.pushButton_12, 2, 3, 1, 1)
#         self.line1 = QtWidgets.QFrame(self.widget3)
#         self.line1.setEnabled(False)
#         self.line1.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line1.setObjectName("line")
#         self.horizontalLayout_5.addWidget(self.line1)
#
#         # 左上区域
#         self.widget1 = QtWidgets.QWidget(self.splitter1)
#         self.widget1.setObjectName("widget1")
#         self.widget1.resize(int(self.width / 1.6), int(self.height / 1.5))
#         self.widget1.setMinimumWidth(700)
#         self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
#         self.horizontalLayout_4.setGeometry(QtCore.QRect(10, 11, 800, 671))
#         self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout_4.setObjectName("horizontalLayout_4")
#         self.verticalLayout = QtWidgets.QVBoxLayout()
#         self.verticalLayout.setObjectName("verticalLayout")
#         self.hlayoutwidget = QtWidgets.QWidget(self.widget1)
#         self.hlayoutwidget.setObjectName("hlayoutwidget")
#         self.hLayout1 = QtWidgets.QHBoxLayout(self.hlayoutwidget)
#         self.hLayout1.setContentsMargins(0, 0, 0, 0)
#         self.hLayout1.setObjectName("hLayout1")
#         self.label_8 = QtWidgets.QLabel(self.hlayoutwidget)
#         self.label_8.setObjectName("label_8")
#         self.hLayout1.addWidget(self.label_8)
#         self.verticalLayout.addWidget(self.hlayoutwidget)
#         self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget1)
#         self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 20, 361, 61))
#         self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
#         self.verticalLayout.addWidget(self.horizontalLayoutWidget)
#         self.pyqtgraph1 = pg.GraphicsLayoutWidget(self.widget1)
#         self.pyqtgraph1.setObjectName("pyqtgraph1")
#         self.pyqtgraph1.setBackground('#F8F8FF')
#         self.verticalLayout.addWidget(self.pyqtgraph1)
#         self.progressBar = QtWidgets.QProgressBar(self.widget1)
#         self.progressBar.setProperty("value", 24)
#         self.progressBar.setObjectName("progressBar")
#         self.verticalLayout.addWidget(self.progressBar)
#         self.line_2 = QtWidgets.QFrame(self.widget1)
#         self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line_2.setObjectName("line_2")
#         self.verticalLayout.addWidget(self.line_2)
#         self.horizontalLayout = QtWidgets.QHBoxLayout()
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.pushButton = QtWidgets.QPushButton(self.widget1)
#         self.pushButton.setMaximumSize(200, 30)
#         self.pushButton.setObjectName("pushButton")
#         self.horizontalLayout.addWidget(self.pushButton)
#         self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_2.setMaximumSize(200, 30)
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.horizontalLayout.addWidget(self.pushButton_2)
#         self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_4.setMaximumSize(200, 30)
#         self.pushButton_4.setObjectName("pushButton_4")
#         self.horizontalLayout.addWidget(self.pushButton_4)
#         self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_3.setMaximumSize(200, 30)
#         self.pushButton_3.setObjectName("pushButton_3")
#         self.horizontalLayout.addWidget(self.pushButton_3)
#         self.pushButton_15 = QtWidgets.QPushButton(self.widget1)
#         self.pushButton_15.setMaximumSize(200, 30)
#         self.pushButton_15.setText('下一步')
#         self.horizontalLayout.addWidget(self.pushButton_15)
#         self.verticalLayout.addLayout(self.horizontalLayout)
#         self.horizontalLayout_4.addLayout(self.verticalLayout)
#         self.line = QtWidgets.QFrame(self.widget1)
#         self.line.setEnabled(False)
#         self.line.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line.setObjectName("line")
#         self.horizontalLayout_4.addWidget(self.line)
#         self.widget1.hide()
#
#         # 第二步
#         self.widget4 = QtWidgets.QWidget(self.splitter1)
#         self.widget4.resize(int(self.width / 1.6), int(self.height / 1.5))
#         self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.widget4)
#         self.horizontalLayout_51.setGeometry(QtCore.QRect(10, 11, 800, 671))
#         self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
#         self.gridLayout101 = QtWidgets.QGridLayout()
#         self.qtext1 = QtWidgets.QTextEdit()
#         self.qtext1.setText('''
#         第二步，将矢网的port1和Tx电缆连接，将矢网的port2端口和Rx电缆连接。
#         将2根线缆直接相连，测出30-1000MHz的矢网的数值。
#
#         ''')
#         self.qtext1.setReadOnly(True)
#         # self.qtext1.setEnabled(False)
#         self.qtext1.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
#         self.gridLayout101.addWidget(self.qtext1, 0, 0, 1, 4)
#         self.horizontalLayout_51.addLayout(self.gridLayout101)
#         self.label_101 = QtWidgets.QLabel()
#         self.gridLayout101.addWidget(self.label_101, 1, 0, 1, 4)
#         jpg1 = QtGui.QPixmap('h:/bishe/img/zhijie.jpg').scaled(700, 400)
#         self.label_101.setPixmap(jpg1)
#         self.pushButton_13 = QtWidgets.QPushButton(self.widget4)
#         self.pushButton_13.setText('上一步')
#         self.gridLayout101.addWidget(self.pushButton_13, 2, 2, 1, 1)
#         self.pushButton_14 = QtWidgets.QPushButton(self.widget4)
#         self.pushButton_14.setText('下一步')
#         self.gridLayout101.addWidget(self.pushButton_14, 2, 3, 1, 1)
#         self.line11 = QtWidgets.QFrame(self.widget4)
#         self.line11.setEnabled(False)
#         self.line11.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line11.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line11.setObjectName("line")
#         self.horizontalLayout_51.addWidget(self.line11)
#         self.widget4.hide()
#
# #         # 第三步
# #         self.widget5 = QtWidgets.QWidget(self.splitter1)
# #         self.widget5.resize(int(self.width / 1.6), int(self.height / 1.5))
# #         self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget5)
# #         self.horizontalLayout_6.setGeometry(QtCore.QRect(10, 11, 800, 671))
# #         self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
# #         self.gridlayout11 = QtWidgets.QGridLayout()
# #         self.qtext2 = QtWidgets.QTextEdit()
# #         self.qtext2.setText(''' 第三步：参考天线测量
# # 整个测量系统配置如下：
# # •	接上转台上的接口。
# # •	转台电缆接10 dB的衰减器。
# # •	通过一根硬的电缆把参考天线连到衰减器。
# # •	参考天线要放置稳定，并且与阵列探头对正。
# # •	外加电缆的一端接到矢网的Port 2，另一端通过一个N阴头 / N阴头转接头连到Rx电缆。
# # •	Rx电缆的一端连到外加电缆，另一端连到到天线测量系统的Rx channel Port。
# # •	Tx电缆连接矢网的Port 1到天线测量系统的Tx channel Port。
# # 点击Next >> 开始测量。
# # 测量完毕后，点击Next >> 到下一步。
# # 对每一根参考天线，重复此步骤。
# #                        ''')
# #         self.qtext2.setReadOnly(True)
# #         # self.qtext2.setEnabled(False)
# #         self.qtext2.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
# #         self.gridlayout11.addWidget(self.qtext2, 0, 0, 1, 4)
# #         self.horizontalLayout_6.addLayout(self.gridlayout11)
# #         self.label_11 = QtWidgets.QLabel()
# #         self.gridlayout11.addWidget(self.label_11, 1, 0, 1, 4)
# #         jpg1 = QtGui.QPixmap('e:/bishe/img/cankao.jpg').scaled(700, 400)
# #         self.label_11.setPixmap(jpg1)
# #         self.pushButton_16 = QtWidgets.QPushButton(self.widget5)
# #         self.pushButton_16.setText('上一步')
# #         self.gridlayout11.addWidget(self.pushButton_16, 2, 2, 1, 1)
# #         self.pushButton_17 = QtWidgets.QPushButton(self.widget5)
# #         self.pushButton_17.setText('下一步')
# #         self.gridlayout11.addWidget(self.pushButton_17, 2, 3, 1, 1)
# #         self.line2 = QtWidgets.QFrame(self.widget5)
# #         self.line2.setEnabled(False)
# #         self.line2.setFrameShape(QtWidgets.QFrame.VLine)
# #         self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
# #         self.line2.setObjectName("line")
# #         self.horizontalLayout_6.addWidget(self.line2)
# #         self.widget5.hide()
# #
# #         # 第四步
# #         self.widget6 = QtWidgets.QWidget(self.splitter1)
# #         self.widget6.resize(int(self.width / 1.6), int(self.height / 1.5))
# #         self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget6)
# #         self.horizontalLayout_7.setGeometry(QtCore.QRect(10, 11, 800, 671))
# #         self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
# #         self.gridlayout12 = QtWidgets.QGridLayout()
# #         self.qtext3 = QtWidgets.QTextEdit()
# #         self.qtext3.setText(''' 第四步：整个测量系统配置如下：
# # •	接通专门的转台接口
# # •	装上移动电话转台接口
# # •	把转台天线接在转台电缆上
# # •	Tx电缆连接矢网的Port 1到天线测量系统的Tx channel Port。
# # •	Rx电缆连接矢网的Port 2到天线测量系统的Rx channel Port。
# #                                ''')
# #         self.qtext3.setReadOnly(True)
# #         # self.qtext3.setEnabled(False)
# #         self.qtext3.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
# #         self.gridlayout12.addWidget(self.qtext3, 0, 0, 1, 4)
# #         self.horizontalLayout_7.addLayout(self.gridlayout12)
# #         self.label_11 = QtWidgets.QLabel()
# #         self.gridlayout12.addWidget(self.label_11, 1, 0, 1, 4)
# #         jpg2 = QtGui.QPixmap('e:/bishe/img/tianxian.jpg').scaled(700, 400)
# #         self.label_11.setPixmap(jpg2)
# #         self.pushButton_18 = QtWidgets.QPushButton(self.widget6)
# #         self.pushButton_18.setText('上一步')
# #         self.gridlayout12.addWidget(self.pushButton_18, 2, 2, 1, 1)
# #         self.pushButton_19 = QtWidgets.QPushButton(self.widget6)
# #         self.pushButton_19.setText('下一步')
# #         self.gridlayout12.addWidget(self.pushButton_19, 2, 3, 1, 1)
# #         self.line3 = QtWidgets.QFrame(self.widget6)
# #         self.line3.setEnabled(False)
# #         self.line3.setFrameShape(QtWidgets.QFrame.VLine)
# #         self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
# #         self.line3.setObjectName("line")
# #         self.horizontalLayout_7.addWidget(self.line3)
# #         self.widget6.hide()
#
#         # 结果
#
#         self.widget7 = QtWidgets.QWidget(self.splitter1)
#         self.widget7.setObjectName("widget7")
#         self.widget7.resize(int(self.width / 1.6), int(self.height / 1.5))
#         self.horizontalLayout10_8 = QtWidgets.QHBoxLayout(self.widget7)
#         self.horizontalLayout10_8.setGeometry(QtCore.QRect(10, 11, 800, 671))
#         self.horizontalLayout10_8.setContentsMargins(0, 0, 0, 0)
#         self.horizontalLayout10_8.setObjectName("horizontalLayout10_8")
#         self.verticalLayout10 = QtWidgets.QVBoxLayout()
#         self.verticalLayout10.setObjectName("verticalLayout10")
#         self.hlayoutwidget10 = QtWidgets.QWidget(self.widget7)
#         self.hlayoutwidget10.setObjectName("hlayoutwidget10")
#         self.hLayout11 = QtWidgets.QHBoxLayout(self.hlayoutwidget10)
#         self.hLayout11.setContentsMargins(0, 0, 0, 0)
#         self.hLayout11.setObjectName("hLayout11")
#         self.label_15 = QtWidgets.QLabel(self.hlayoutwidget10)
#         self.label_15.setObjectName("label_15")
#         self.hLayout11.addWidget(self.label_15)
#         self.verticalLayout10.addWidget(self.hlayoutwidget10)
#         self.horizontalLayout10Widget10 = QtWidgets.QWidget(self.widget7)
#         self.horizontalLayout10Widget10.setGeometry(QtCore.QRect(80, 20, 361, 61))
#         self.horizontalLayout10Widget10.setObjectName("horizontalLayout10Widget10")
#         self.verticalLayout10.addWidget(self.horizontalLayout10Widget10)
#         self.pyqtgraph2 = pg.GraphicsLayoutWidget(self.widget7)
#         self.pyqtgraph2.setObjectName("pyqtgraph2")
#         self.pyqtgraph2.setBackground('#F8F8FF')
#         self.verticalLayout10.addWidget(self.pyqtgraph2)
#         self.horizontalLayout10 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout10.setObjectName("horizontalLayout10")
#         self.pushButton_20 = QtWidgets.QPushButton(self.widget7)
#         self.pushButton_20.setMaximumSize(200, 30)
#         self.horizontalLayout10.addWidget(self.pushButton_20)
#         self.verticalLayout10.addLayout(self.horizontalLayout10)
#         self.horizontalLayout10_8.addLayout(self.verticalLayout10)
#         self.line5 = QtWidgets.QFrame(self.widget7)
#         self.line5.setEnabled(False)
#         self.line5.setFrameShape(QtWidgets.QFrame.VLine)
#         self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line5.setObjectName("line5")
#         self.horizontalLayout10_8.addWidget(self.line5)
#         self.widget7.hide()
#
#         # 设置部分
#         self.widget2 = QtWidgets.QWidget(self.splitter1)
#         self.widget2.setMinimumSize(QtCore.QSize(300, 300))
#         self.widget2.setObjectName("widget2")
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
#         self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
#         self.verticalLayout_2.setObjectName("verticalLayout_2")
#         self.formGroupBox = QtWidgets.QGroupBox(self.widget2)
#         self.formGroupBox.setObjectName("formGroupBox")
#         self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
#         self.gridLayout.setObjectName("gridLayout")
#         self.Label_11 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_11.setObjectName("Label_11")
#         self.gridLayout.addWidget(self.Label_11, 0, 0, 1, 1)
#         self.LineEdit_11 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_11.setObjectName("LineEdit_11")
#         self.gridLayout.addWidget(self.LineEdit_11, 0, 2, 1, 1)
#         self.Label_12 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_12.setObjectName("Label_12")
#         self.gridLayout.addWidget(self.Label_12, 1, 0, 1, 1)
#         self.Label_13 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_13.setObjectName("Label_12")
#         self.gridLayout.addWidget(self.Label_13, 1, 3, 1, 1)
#         self.LineEdit_12 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_12.setObjectName("LineEdit_12")
#         self.gridLayout.addWidget(self.LineEdit_12, 1, 2, 1, 1)
#         self.LineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_2.setObjectName("LineEdit_2")
#         self.gridLayout.addWidget(self.LineEdit_2, 3, 2, 1, 1)
#         self.Label_7 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_7.setObjectName("Label_7")
#         self.gridLayout.addWidget(self.Label_7, 8, 0, 1, 1)
#         self.LineEdit_10 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_10.setObjectName("LineEdit_10")
#         self.gridLayout.addWidget(self.LineEdit_10, 12, 2, 1, 1)
#         self.label_7 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_7.setObjectName("label_7")
#         self.gridLayout.addWidget(self.label_7, 9, 3, 1, 1)
#         self.LineEdit_6 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_6.setObjectName("LineEdit_6")
#         self.gridLayout.addWidget(self.LineEdit_6, 7, 2, 1, 1)
#         self.label_6 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_6.setObjectName("label_6")
#         self.gridLayout.addWidget(self.label_6, 8, 3, 1, 1)
#         self.label_3 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_3.setObjectName("label_3")
#         self.gridLayout.addWidget(self.label_3, 5, 3, 1, 1)
#         self.Label_9 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_9.setObjectName("Label_9")
#         self.gridLayout.addWidget(self.Label_9, 11, 0, 1, 1)
#         self.LineEdit_8 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_8.setObjectName("LineEdit_8")
#         self.gridLayout.addWidget(self.LineEdit_8, 9, 2, 1, 1)
#         self.label_2 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_2.setObjectName("label_2")
#         self.gridLayout.addWidget(self.label_2, 3, 3, 1, 1)
#         self.LineEdit_7 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_7.setObjectName("LineEdit_7")
#         self.gridLayout.addWidget(self.LineEdit_7, 8, 2, 1, 1)
#         self.LineEdit_9 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_9.setObjectName("LineEdit_9")
#         self.gridLayout.addWidget(self.LineEdit_9, 11, 2, 1, 1)
#         self.Label_8 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_8.setObjectName("Label_8")
#         self.gridLayout.addWidget(self.Label_8, 9, 0, 1, 1)
#         self.LineEdit_4 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_4.setObjectName("LineEdit_4")
#         self.gridLayout.addWidget(self.LineEdit_4, 5, 2, 1, 1)
#         self.Label_4 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_4.setObjectName("Label_4")
#         self.gridLayout.addWidget(self.Label_4, 5, 0, 1, 1)
#         self.LineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit_3.setObjectName("LineEdit_3")
#         self.gridLayout.addWidget(self.LineEdit_3, 4, 2, 1, 1)
#         self.label_5 = QtWidgets.QLabel(self.formGroupBox)
#         self.label_5.setObjectName("label_5")
#         self.gridLayout.addWidget(self.label_5, 7, 3, 1, 1)
#         self.Label_2 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_2.setObjectName("Label_2")
#         self.gridLayout.addWidget(self.Label_2, 3, 0, 1, 1)
#         self.Label_10 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_10.setObjectName("Label_10")
#         self.gridLayout.addWidget(self.Label_10, 12, 0, 1, 1)
#         self.LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
#         self.LineEdit.setObjectName("LineEdit")
#         self.gridLayout.addWidget(self.LineEdit, 2, 2, 1, 1)
#         self.Label_6 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_6.setObjectName("Label_6")
#         self.gridLayout.addWidget(self.Label_6, 7, 0, 1, 1)
#         self.Label_3 = QtWidgets.QLabel(self.formGroupBox)
#         self.Label_3.setObjectName("Label_3")
#         self.gridLayout.addWidget(self.Label_3, 4, 0, 1, 1)
#         self.label = QtWidgets.QLabel(self.formGroupBox)
#         self.label.setObjectName("label")
#         self.gridLayout.addWidget(self.label, 4, 3, 1, 1)
#         self.Label = QtWidgets.QLabel(self.formGroupBox)
#         self.Label.setObjectName("Label")
#         self.gridLayout.addWidget(self.Label, 2, 0, 1, 1)
#         self.verticalLayout_2.addWidget(self.formGroupBox)
#         self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
#         self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
#         self.horizontalLayout_3.setObjectName("horizontalLayout_3")
#         self.pushButton_6 = QtWidgets.QPushButton(self.widget2)
#         self.pushButton_6.setObjectName("pushButton_6")
#         self.pushButton_6.setMaximumWidth(180)
#         self.horizontalLayout_3.addWidget(self.pushButton_6)
#         self.pushButton_7 = QtWidgets.QPushButton(self.widget2)
#         self.pushButton_7.setObjectName("pushButton_7")
#         self.pushButton_7.setMaximumWidth(180)
#         self.horizontalLayout_3.addWidget(self.pushButton_7)
#         self.pushButton_9 = QtWidgets.QPushButton(self.widget2)
#         self.pushButton_9.setObjectName("pushButton_9")
#         self.pushButton_9.setMaximumWidth(180)
#         self.horizontalLayout_3.addWidget(self.pushButton_9)
#         self.verticalLayout_2.addLayout(self.horizontalLayout_3)
#
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 23))
#         self.menubar.setObjectName("menubar")
#         self.menu = QtWidgets.QMenu(self.menubar)
#         self.menu.setObjectName("menu")
#         self.menu_3 = QtWidgets.QMenu(self.menubar)
#         self.menu_3.setObjectName("menu_3")
#         self.menu_4 = QtWidgets.QMenu(self.menubar)
#         self.menu_4.setObjectName("menu_4")
#         MainWindow.setMenuBar(self.menubar)
#         self.statusbar = QtWidgets.QStatusBar(MainWindow)
#         self.statusbar.setObjectName("statusbar")
#         MainWindow.setStatusBar(self.statusbar)
#         self.action1 = QtWidgets.QAction(MainWindow)
#         self.action1.setObjectName("action1")
#         self.action2 = QtWidgets.QAction(MainWindow)
#         self.action2.setObjectName("action2")
#         self.action3 = QtWidgets.QAction(MainWindow)
#         self.action3.setObjectName("action3")
#         self.action4 = QtWidgets.QAction(MainWindow)
#         self.action4.setObjectName("action4")
#         self.action5 = QtWidgets.QAction(MainWindow)
#         self.action5.setObjectName("action5")
#         self.action1_2 = QtWidgets.QAction(MainWindow)
#         self.action1_2.setObjectName("action1_2")
#         self.action2_2 = QtWidgets.QAction(MainWindow)
#         self.action2_2.setObjectName("action2_2")
#         self.action3_2 = QtWidgets.QAction(MainWindow)
#         self.action3_2.setObjectName("action3_2")
#         self.action4_2 = QtWidgets.QAction(MainWindow)
#         self.action4_2.setObjectName("action4_2")
#         self.action5_2 = QtWidgets.QAction(MainWindow)
#         self.action5_2.setObjectName("action5_2")
#         self.actionconnect = QtWidgets.QAction(MainWindow)
#         self.actionconnect.setObjectName("actionconnect")
#         self.actiondisconnect = QtWidgets.QAction(MainWindow)
#         self.actiondisconnect.setObjectName("actiondisconnect")
#         self.actionhelp = QtWidgets.QAction(MainWindow)
#         self.actionhelp.setObjectName("actionhelp")
#         self.actionopen = QtWidgets.QAction(MainWindow)
#         self.actionopen.setCheckable(False)
#         self.actionopen.setObjectName("actionopen")
#         self.action = QtWidgets.QAction(MainWindow)
#         self.action.setObjectName("action")
#         self.action1_3 = QtWidgets.QAction(MainWindow)
#         self.action1_3.setObjectName("action1_3")
#         self.action1_4 = QtWidgets.QAction(MainWindow)
#         self.action1_4.setObjectName("action1_4")
#         self.action_3 = QtWidgets.QAction(MainWindow)
#         self.action_3.setObjectName("action_3")
#         self.menu.addAction(self.actionopen)
#         self.menu.addSeparator()
#         self.menu.addAction(self.action1)
#         self.menu.addAction(self.action2)
#         self.menu.addAction(self.action)
#         self.menu.addAction(self.action3)
#         self.menu.addSeparator()
#         self.menu.addAction(self.action4)
#         self.menu.addSeparator()
#         self.menu.addAction(self.action5)
#         self.menu_3.addAction(self.actionhelp)
#         self.menu_4.addAction(self.actionconnect)
#         self.menu_4.addAction(self.action_3)
#         self.menubar.addAction(self.menu.menuAction())
#         self.menubar.addAction(self.menu_4.menuAction())
#         self.menubar.addAction(self.menu_3.menuAction())
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#         MainWindow.setTabOrder(self.LineEdit_2, self.LineEdit_3)
#         MainWindow.setTabOrder(self.LineEdit_3, self.LineEdit_4)
#         MainWindow.setTabOrder(self.LineEdit_4, self.LineEdit_6)
#         MainWindow.setTabOrder(self.LineEdit_6, self.LineEdit_7)
#         MainWindow.setTabOrder(self.LineEdit_7, self.LineEdit_8)
#         MainWindow.setTabOrder(self.LineEdit_8, self.LineEdit_9)
#         MainWindow.setTabOrder(self.LineEdit_9, self.LineEdit_10)
#         MainWindow.setTabOrder(self.LineEdit_10, self.pushButton_6)
#         MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
#         MainWindow.setTabOrder(self.pushButton_7, self.pushButton)
#         MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
#         MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "归一化场地衰减测试"))
#         self.pushButton_8.setText(_translate("MainWindow", "读取结果"))
#         self.pushButton_11.setText(_translate("MainWindow", "重新开始测量"))
#         self.pushButton_5.setText(_translate("MainWindow", "保存结果"))
#         self.Label_11.setText(_translate("MainWindow", "模式"))
#         self.Label_12.setText(_translate("MainWindow", "天线增益"))
#         self.Label_13.setText(_translate("MainWindow", "dB"))
#         # self.label_8.setText(_translate("MainWindow", "TextLabel"))
#         self.pushButton.setText(_translate("MainWindow", "开始"))
#         self.pushButton_2.setText(_translate("MainWindow", "暂停"))
#         self.pushButton_4.setText(_translate("MainWindow", "继续"))
#         self.pushButton_3.setText(_translate("MainWindow", "结束"))
#         self.Label_7.setText(_translate("MainWindow", "输出功率:"))
#         self.label_7.setText(_translate("MainWindow", "ns"))
#         self.label_6.setText(_translate("MainWindow", "dBm"))
#         self.label_3.setText(_translate("MainWindow", "kHz"))
#         self.Label_9.setText(_translate("MainWindow", "扫描点数:"))
#         self.label_2.setText(_translate("MainWindow", "MHz"))
#         self.Label_8.setText(_translate("MainWindow", "电延时:"))
#         self.Label_4.setText(_translate("MainWindow", "中频带宽:"))
#         self.label_5.setText(_translate("MainWindow", ""))
#         self.Label_2.setText(_translate("MainWindow", "起始频率:"))
#         self.Label_10.setText(_translate("MainWindow", "文件名:"))
#         self.Label_6.setText(_translate("MainWindow", "天线位置:"))
#         self.Label_3.setText(_translate("MainWindow", "终止频率:"))
#         self.label.setText(_translate("MainWindow", "MHz"))
#         self.Label.setText(_translate("MainWindow", "地址:"))
#         self.label_8.setText(_translate("MainWindow", "准备阶段"))
#         self.pushButton_6.setText(_translate("MainWindow", "保存设置"))
#         self.pushButton_7.setText(_translate("MainWindow", "读取设置"))
#         self.pushButton_9.setText(_translate("MainWindow", "设置另存为..."))
#         self.menu.setTitle(_translate("MainWindow", "开始"))
#         self.menu_3.setTitle(_translate("MainWindow", "帮助"))
#         self.menu_4.setTitle(_translate("MainWindow", "设置"))
#         self.action1.setText(_translate("MainWindow", "开始"))
#         self.action2.setText(_translate("MainWindow", "暂停"))
#         self.action3.setText(_translate("MainWindow", "结束"))
#         self.action4.setText(_translate("MainWindow", "保存测量结果"))
#         self.action5.setText(_translate("MainWindow", "退出"))
#         self.action1_2.setText(_translate("MainWindow", "1"))
#         self.action2_2.setText(_translate("MainWindow", "2"))
#         self.action3_2.setText(_translate("MainWindow", "3"))
#         self.action4_2.setText(_translate("MainWindow", "4"))
#         self.action5_2.setText(_translate("MainWindow", "5"))
#         self.actionconnect.setText(_translate("MainWindow", "连接设置"))
#         self.actiondisconnect.setText(_translate("MainWindow", "断开连接"))
#         self.actionhelp.setText(_translate("MainWindow", "帮助信息"))
#         self.actionopen.setText(_translate("MainWindow", "打开文件"))
#         self.action.setText(_translate("MainWindow", "继续"))
#         self.action1_3.setText(_translate("MainWindow", "1"))
#         self.action1_4.setText(_translate("MainWindow", "1"))
#         self.action_3.setText(_translate("MainWindow", "保存设置"))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowF.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.width = QtWidgets.QApplication.desktop().screenGeometry().width()
        self.height = QtWidgets.QApplication.desktop().screenGeometry().height()
        MainWindow.resize(self.width / 1.5, self.height / 1.1)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.splitter1 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.gridLayout3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout3.setObjectName("gridLayout3")
        self.gridLayout3.addWidget(self.splitter1, 0, 0, 3, 3)

        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout3.addWidget(self.line_3, 3, 0, 1, 3)

        self.ww = QtWidgets.QWidget(self.centralwidget)
        self.gridLayout3.addWidget(self.ww, 4, 0, 1, 1)
        self.h1 = QtWidgets.QHBoxLayout(self.ww)

        self.lab1 = QtWidgets.QLabel()
        jpg5 = QtGui.QPixmap('./img/cha.jpg').scaled(48, 48)
        self.lab1.setPixmap(jpg5)
        self.h1.addWidget(self.lab1)
        self.lab2 = QtWidgets.QLabel()
        self.lab2.setText('检测到未连接')
        self.lab2.setStyleSheet("QLabel{color:rgb(255,0,0)}")
        self.h1.addWidget(self.lab2)
        self.pbtn1 = QtWidgets.QPushButton()
        self.pbtn1.setMinimumWidth(80)
        self.pbtn1.setMinimumHeight(25)
        self.pbtn1.setText('重新连接')
        self.h1.addWidget(self.pbtn1)



        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(350, 50)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout3.addWidget(self.widget, 4, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setMinimumHeight(25)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_2.addWidget(self.pushButton_11)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setMinimumHeight(25)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setMinimumHeight(25)
        self.horizontalLayout_2.addWidget(self.pushButton_5)

        # 第一步
        self.widget3 = QtWidgets.QWidget(self.splitter1)
        self.widget3.setObjectName("widget3")
        self.widget3.resize(int(self.width / 1.6), int(self.height / 1.5))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_5.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout10 = QtWidgets.QGridLayout()
        self.qtext = QtWidgets.QTextEdit()
        self.qtext.setText('''第一步：只有Rx电缆的测量
整个测量系统配置如下：
•	转台上未接任何接口。
•	转台电缆接10 dB的衰减器。
•	外加的电缆从矢网的Port 1到衰减器（需要SMA阳头 / N阴头转接器）。 
•	Rx电缆 （专门用于有源测量）从矢网的Port 2到天线测量系统的Rx channel port。
•	将暗室的通道改为Rx电缆
•	点击下一步
''')
        self.qtext.setReadOnly(True)
        # self.qtext.setEnabled(False)
        self.qtext.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
        self.gridLayout10.addWidget(self.qtext, 0, 0, 1, 4)
        self.horizontalLayout_5.addLayout(self.gridLayout10)
        self.label_10 = QtWidgets.QLabel()
        self.gridLayout10.addWidget(self.label_10, 1, 0, 1, 4)
        jpg = QtGui.QPixmap('./img/nsa.jpg').scaled(700, 380)
        self.label_10.setPixmap(jpg)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_12.setText('开始测量')
        self.gridLayout10.addWidget(self.pushButton_12, 2, 3, 1, 1)
        self.line1 = QtWidgets.QFrame(self.widget3)
        self.line1.setEnabled(False)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line1)

        # 左上区域
        self.widget1 = QtWidgets.QWidget(self.splitter1)
        self.widget1.setObjectName("widget1")
        self.widget1.resize(int(self.width / 1.6), int(self.height / 1.5))
        self.widget1.setMinimumWidth(700)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.hlayoutwidget = QtWidgets.QWidget(self.widget1)
        self.hlayoutwidget.setObjectName("hlayoutwidget")
        self.hLayout1 = QtWidgets.QHBoxLayout(self.hlayoutwidget)
        self.hLayout1.setContentsMargins(0, 0, 0, 0)
        self.hLayout1.setObjectName("hLayout1")
        self.label_8 = QtWidgets.QLabel(self.hlayoutwidget)
        self.label_8.setObjectName("label_8")
        self.hLayout1.addWidget(self.label_8)
        self.verticalLayout.addWidget(self.hlayoutwidget)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget1)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 20, 361, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout.addWidget(self.horizontalLayoutWidget)
        self.pyqtgraph1 = pg.GraphicsLayoutWidget(self.widget1)
        self.pyqtgraph1.setObjectName("pyqtgraph1")
        self.pyqtgraph1.setBackground('#F8F8FF')
        self.verticalLayout.addWidget(self.pyqtgraph1)
        self.progressBar = QtWidgets.QProgressBar(self.widget1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.line_2 = QtWidgets.QFrame(self.widget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setMaximumSize(180, 30)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setMaximumSize(200, 30)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setText('下个位置')
        self.horizontalLayout.addWidget(self.pushButton_2)
        # self.pushButton_4 = QtWidgets.QPushButton(self.widget1)
        # self.pushButton_4.setMaximumSize(200, 30)
        # self.pushButton_4.setObjectName("pushButton_4")
        # self.horizontalLayout.addWidget(self.pushButton_4)
        # self.pushButton_3 = QtWidgets.QPushButton(self.widget1)
        # self.pushButton_3.setMaximumSize(200, 30)
        # self.pushButton_3.setObjectName("pushButton_3")
        # self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_15.setMaximumSize(180, 30)
        self.pushButton_15.setText('下一步')
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.widget1)
        self.line.setEnabled(False)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.widget1.hide()

        # 第二步
        self.widget4 = QtWidgets.QWidget(self.splitter1)
        self.widget4.resize(int(self.width / 1.6), int(self.height / 1.5))
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.widget4)
        self.horizontalLayout_51.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.gridLayout101 = QtWidgets.QGridLayout()
        self.qtext1 = QtWidgets.QTextEdit()
        self.qtext1.setText('''第二步：只有Tx电缆的测量
整个测量系统配置如下：
•	转台上未接任何接口。
•	转台电缆接10 dB的衰减器。
•	外加的电缆从矢网的Port 1到衰减器（需要SMA阳头 / N阴头转接器）  
•	Tx电缆 （专门用于有源测量）从矢网的Port 1到天线测量系统的TX channel Port。
•	将暗室的通道改为Tx电缆
•	点击下一步开始测量。

        ''')
        self.qtext1.setReadOnly(True)
        # self.qtext1.setEnabled(False)
        self.qtext1.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
        self.gridLayout101.addWidget(self.qtext1, 0, 0, 1, 4)
        self.horizontalLayout_51.addLayout(self.gridLayout101)
        self.label_101 = QtWidgets.QLabel()
        self.gridLayout101.addWidget(self.label_101, 1, 0, 1, 4)
        jpg1 = QtGui.QPixmap('./img/tx.jpg').scaled(700, 380)
        self.label_101.setPixmap(jpg1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_13.setText('上一步')
        self.gridLayout101.addWidget(self.pushButton_13, 2, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_14.setText('下一步')
        self.gridLayout101.addWidget(self.pushButton_14, 2, 3, 1, 1)
        self.line11 = QtWidgets.QFrame(self.widget4)
        self.line11.setEnabled(False)
        self.line11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line11.setObjectName("line")
        self.horizontalLayout_51.addWidget(self.line11)
        self.widget4.hide()

        # 第三步
        self.widget5 = QtWidgets.QWidget(self.splitter1)
        self.widget5.resize(int(self.width / 1.6), int(self.height / 1.5))
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget5)
        self.horizontalLayout_6.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridlayout11 = QtWidgets.QGridLayout()
        self.qtext2 = QtWidgets.QTextEdit()
        self.qtext2.setText(''' 第三步：参考天线测量Rx
整个测量系统配置如下：
•	接上转台上的接口。
•	转台电缆接10 dB的衰减器。
•	通过一根硬的电缆把参考天线连到衰减器。
•	参考天线要放置稳定，并且与阵列探头对正。
•	外加电缆的一端接到矢网的Port 2，另一端通过一个N阴头 / N阴头转接头连到Rx电缆。
•	Rx电缆的一端连到外加电缆，另一端连到到天线测量系统的Rx channel Port。
•	Tx电缆连接矢网的Port 1到天线测量系统的Tx channel Port。
•	将暗室的通道改为Rx电缆
•	点击下一步 开始测量。

                       ''')
        self.qtext2.setReadOnly(True)
        # self.qtext2.setEnabled(False)
        self.qtext2.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
        self.gridlayout11.addWidget(self.qtext2, 0, 0, 1, 4)
        self.horizontalLayout_6.addLayout(self.gridlayout11)
        self.label_11 = QtWidgets.QLabel()
        self.gridlayout11.addWidget(self.label_11, 1, 0, 1, 4)
        jpg1 = QtGui.QPixmap('./img/cankao.jpg').scaled(700, 380)
        self.label_11.setPixmap(jpg1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget5)
        self.pushButton_16.setText('上一步')
        self.gridlayout11.addWidget(self.pushButton_16, 2, 2, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget5)
        self.pushButton_17.setText('下一步')
        self.gridlayout11.addWidget(self.pushButton_17, 2, 3, 1, 1)
        self.line2 = QtWidgets.QFrame(self.widget5)
        self.line2.setEnabled(False)
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line2)
        self.widget5.hide()

        # 第四步
        self.widget6 = QtWidgets.QWidget(self.splitter1)
        self.widget6.resize(int(self.width / 1.6), int(self.height / 1.5))
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget6)
        self.horizontalLayout_7.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridlayout12 = QtWidgets.QGridLayout()
        self.qtext3 = QtWidgets.QTextEdit()
        self.qtext3.setText(''' 第四步：整个测量系统配置如下：
•	保持第三步的设置不变，将配置的模式改为S12，
•	将暗室的通道变为TX模式
•	点击下一步进行测量。
                               ''')
        self.qtext3.setReadOnly(True)
        # self.qtext3.setEnabled(False)
        self.qtext3.setStyleSheet("QTextEdit{color:rgb(0,0,0);}")
        self.gridlayout12.addWidget(self.qtext3, 0, 0, 1, 4)
        self.horizontalLayout_7.addLayout(self.gridlayout12)
        self.label_11 = QtWidgets.QLabel()
        self.gridlayout12.addWidget(self.label_11, 1, 0, 1, 4)
        jpg2 = QtGui.QPixmap('./img/cankao.jpg').scaled(700, 380)
        self.label_11.setPixmap(jpg2)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget6)
        self.pushButton_18.setText('上一步')
        self.gridlayout12.addWidget(self.pushButton_18, 2, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget6)
        self.pushButton_19.setText('下一步')
        self.gridlayout12.addWidget(self.pushButton_19, 2, 3, 1, 1)
        self.line3 = QtWidgets.QFrame(self.widget6)
        self.line3.setEnabled(False)
        self.line3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line3)
        self.widget6.hide()

        # 结果

        self.widget7 = QtWidgets.QWidget(self.splitter1)
        self.widget7.setObjectName("widget7")
        self.widget7.resize(int(self.width / 1.6), int(self.height / 1.5))
        self.horizontalLayout10_8 = QtWidgets.QHBoxLayout(self.widget7)
        self.horizontalLayout10_8.setGeometry(QtCore.QRect(10, 11, 800, 671))
        self.horizontalLayout10_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout10_8.setObjectName("horizontalLayout10_8")
        self.verticalLayout10 = QtWidgets.QVBoxLayout()
        self.verticalLayout10.setObjectName("verticalLayout10")
        self.hlayoutwidget10 = QtWidgets.QWidget(self.widget7)
        self.hlayoutwidget10.setObjectName("hlayoutwidget10")
        self.hLayout11 = QtWidgets.QHBoxLayout(self.hlayoutwidget10)
        self.hLayout11.setContentsMargins(0, 0, 0, 0)
        self.hLayout11.setObjectName("hLayout11")
        self.label_15 = QtWidgets.QLabel(self.hlayoutwidget10)
        self.label_15.setObjectName("label_15")
        self.label_15.setText('最终结果')
        self.hLayout11.addWidget(self.label_15)
        self.verticalLayout10.addWidget(self.hlayoutwidget10)
        self.horizontalLayout10Widget10 = QtWidgets.QWidget(self.widget7)
        self.horizontalLayout10Widget10.setGeometry(QtCore.QRect(80, 20, 501, 61))
        self.horizontalLayout10Widget10.setObjectName("horizontalLayout10Widget10")
        self.verticalLayout10.addWidget(self.horizontalLayout10Widget10)
        self.pyqtgraph2 = pg.GraphicsLayoutWidget(self.widget7)
        self.pyqtgraph2.setObjectName("pyqtgraph2")
        self.pyqtgraph2.setBackground('#F8F8FF')
        self.verticalLayout10.addWidget(self.pyqtgraph2)
        self.horizontalLayout10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout10.setObjectName("horizontalLayout10")
        self.pushButton_27 = QtWidgets.QPushButton(self.widget7)
        self.pushButton_27.setMaximumSize(200, 25)
        self.pushButton_27.setMinimumSize(200, 25)
        self.pushButton_27.setText('计算结果')
        self.pushButton_28 = QtWidgets.QPushButton(self.widget7)
        self.pushButton_28.setMaximumSize(200, 25)
        self.pushButton_28.setMinimumSize(200, 25)
        self.pushButton_28.setText('保存结果')
        self.horizontalLayout10.addWidget(self.pushButton_27)
        self.horizontalLayout10.addWidget(self.pushButton_28)
        self.horizontalLayout10.setAlignment(QtCore.Qt.AlignRight)
        self.line_3 = QtWidgets.QFrame(self.widget1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setMinimumWidth(500)
        self.verticalLayout10.addWidget(self.line_3)
        self.verticalLayout10.addLayout(self.horizontalLayout10)
        self.horizontalLayout10_8.addLayout(self.verticalLayout10)
        self.line5 = QtWidgets.QFrame(self.widget7)
        self.line5.setEnabled(False)
        self.line5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line5.setObjectName("line5")
        self.horizontalLayout10_8.addWidget(self.line5)
        self.widget7.hide()

        # 设置部分
        self.widget2 = QtWidgets.QWidget(self.splitter1)
        self.widget2.setMinimumSize(QtCore.QSize(300, 300))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formGroupBox = QtWidgets.QGroupBox(self.widget2)
        self.formGroupBox.setObjectName("formGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_11 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_11.setObjectName("Label_11")
        self.gridLayout.addWidget(self.Label_11, 0, 0, 1, 1)
        self.LineEdit_11 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_11.setObjectName("LineEdit_11")
        self.gridLayout.addWidget(self.LineEdit_11, 0, 2, 1, 1)
        self.Label_12 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_12.setObjectName("Label_12")
        self.gridLayout.addWidget(self.Label_12, 1, 0, 1, 1)
        self.Label_13 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_13.setObjectName("Label_12")
        self.gridLayout.addWidget(self.Label_13, 1, 3, 1, 1)
        self.LineEdit_12 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_12.setObjectName("LineEdit_12")
        self.gridLayout.addWidget(self.LineEdit_12, 1, 2, 1, 1)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.gridLayout.addWidget(self.LineEdit_2, 3, 2, 1, 1)
        self.Label_7 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_7.setObjectName("Label_7")
        self.gridLayout.addWidget(self.Label_7, 8, 0, 1, 1)
        self.LineEdit_10 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_10.setObjectName("LineEdit_10")
        self.gridLayout.addWidget(self.LineEdit_10, 12, 2, 1, 1)
        self.pushbutton_22 = QtWidgets.QPushButton(self.formGroupBox)
        self.pushbutton_22.setText('选择位置...')
        self.gridLayout.addWidget(self.pushbutton_22, 13, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.formGroupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 9, 3, 1, 1)
        self.LineEdit_6 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.gridLayout.addWidget(self.LineEdit_6, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.formGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 8, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 3, 1, 1)
        self.Label_9 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_9.setObjectName("Label_9")
        self.gridLayout.addWidget(self.Label_9, 11, 0, 1, 1)
        self.LineEdit_8 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_8.setObjectName("LineEdit_8")
        self.gridLayout.addWidget(self.LineEdit_8, 9, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 3, 1, 1)
        self.LineEdit_7 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_7.setObjectName("LineEdit_7")
        self.gridLayout.addWidget(self.LineEdit_7, 8, 2, 1, 1)
        self.LineEdit_9 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_9.setObjectName("LineEdit_9")
        self.gridLayout.addWidget(self.LineEdit_9, 11, 2, 1, 1)
        self.Label_8 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_8.setObjectName("Label_8")
        self.gridLayout.addWidget(self.Label_8, 9, 0, 1, 1)
        self.LineEdit_4 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.gridLayout.addWidget(self.LineEdit_4, 5, 2, 1, 1)
        self.Label_4 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_4.setObjectName("Label_4")
        self.gridLayout.addWidget(self.Label_4, 5, 0, 1, 1)
        self.LineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.gridLayout.addWidget(self.LineEdit_3, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.formGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 3, 1, 1)
        self.Label_2 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 3, 0, 1, 1)
        self.Label_10 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_10.setObjectName("Label_10")
        self.gridLayout.addWidget(self.Label_10, 12, 0, 1, 1)
        self.LineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.LineEdit.setObjectName("LineEdit")
        self.gridLayout.addWidget(self.LineEdit, 2, 2, 1, 1)
        self.Label_6 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_6.setObjectName("Label_6")
        self.gridLayout.addWidget(self.Label_6, 7, 0, 1, 1)
        self.Label_3 = QtWidgets.QLabel(self.formGroupBox)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout.addWidget(self.Label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.formGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 3, 1, 1)
        self.Label = QtWidgets.QLabel(self.formGroupBox)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.formGroupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setMaximumWidth(180)
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setMaximumWidth(180)
        self.horizontalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setMaximumWidth(180)
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu1 = QtWidgets.QMenu(self.menubar)
        self.menu1.setTitle("文件")
        self.menu1.setObjectName("menu1")
        self.menu2 = QtWidgets.QMenu(self.menubar)
        self.menu2.setTitle("测量")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setText("系统信息")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setText("重新开始测量")
        # self.action8 = QtWidgets.QAction(MainWindow)
        # self.action8.setText("重新开始测量")
        # self.action9 = QtWidgets.QAction(MainWindow)
        # self.action9.setText("重新开始测量")
        self.actionconnect = QtWidgets.QAction(MainWindow)
        self.actionconnect.setObjectName("actionconnect")
        self.actiondisconnect = QtWidgets.QAction(MainWindow)
        self.actiondisconnect.setObjectName("actiondisconnect")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionopen = QtWidgets.QAction(MainWindow)
        # self.actionopen.setCheckable(False)
        self.actionopen.setObjectName("actionopen")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        # self.action_3 = QtWidgets.QAction(MainWindow)
        # self.action_3.setObjectName("action_3")

        self.menu1.addAction(self.actionopen)
        self.menu1.addSeparator()
        self.menu1.addAction(self.action4)
        self.menu.addAction(self.action6)
        self.menu.addSeparator()
        self.menu.addAction(self.action5)
        self.menu2.addAction(self.action1)
        self.menu2.addAction(self.action2)
        self.menu2.addAction(self.action)
        self.menu2.addAction(self.action3)
        self.menu2.addSeparator()
        self.menu2.addAction(self.action7)
        self.menu_3.addAction(self.actionhelp)
        self.menu_4.addAction(self.actionconnect)
        # self.menu_4.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu1.menuAction())
        self.menubar.addAction(self.menu2.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.LineEdit_2, self.LineEdit_3)
        MainWindow.setTabOrder(self.LineEdit_3, self.LineEdit_4)
        MainWindow.setTabOrder(self.LineEdit_4, self.LineEdit_6)
        MainWindow.setTabOrder(self.LineEdit_6, self.LineEdit_7)
        MainWindow.setTabOrder(self.LineEdit_7, self.LineEdit_8)
        MainWindow.setTabOrder(self.LineEdit_8, self.LineEdit_9)
        MainWindow.setTabOrder(self.LineEdit_9, self.LineEdit_10)
        MainWindow.setTabOrder(self.LineEdit_10, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton)
        # MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        # MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "归一化场地衰减测试"))
        self.pushButton_8.setText(_translate("MainWindow", "读取结果"))
        self.pushButton_11.setText(_translate("MainWindow", "重新开始测量"))
        self.pushButton_5.setText(_translate("MainWindow", "保存结果"))
        self.Label_11.setText(_translate("MainWindow", "模式"))
        self.Label_12.setText(_translate("MainWindow", "天线增益"))
        self.Label_13.setText(_translate("MainWindow", "dB"))
        # self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "开始"))
        # self.pushButton_2.setText(_translate("MainWindow", "暂停"))
        # self.pushButton_4.setText(_translate("MainWindow", "继续"))
        # self.pushButton_3.setText(_translate("MainWindow", "结束"))
        self.Label_7.setText(_translate("MainWindow", "输出功率:"))
        self.label_7.setText(_translate("MainWindow", "ns"))
        self.label_6.setText(_translate("MainWindow", "dBm"))
        self.label_3.setText(_translate("MainWindow", "Hz"))
        self.Label_9.setText(_translate("MainWindow", "扫描点数:"))
        self.label_2.setText(_translate("MainWindow", "MHz"))
        self.Label_8.setText(_translate("MainWindow", "电延时:"))
        self.Label_4.setText(_translate("MainWindow", "中频带宽:"))
        self.label_5.setText(_translate("MainWindow", "次"))
        self.Label_2.setText(_translate("MainWindow", "起始频率:"))
        self.Label_10.setText(_translate("MainWindow", "文件位置:"))
        self.Label_6.setText(_translate("MainWindow", "平均次数:"))
        self.Label_3.setText(_translate("MainWindow", "终止频率:"))
        self.label.setText(_translate("MainWindow", "MHz"))
        self.Label.setText(_translate("MainWindow", "地址:"))
        self.label_8.setText(_translate("MainWindow", "准备阶段"))
        self.pushButton_6.setText(_translate("MainWindow", "保存设置"))
        self.pushButton_7.setText(_translate("MainWindow", "读取设置"))
        self.pushButton_9.setText(_translate("MainWindow", "设置另存为..."))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.menu_4.setTitle(_translate("MainWindow", "连接"))
        self.action1.setText(_translate("MainWindow", "开始"))
        self.action2.setText(_translate("MainWindow", "暂停"))
        self.action3.setText(_translate("MainWindow", "结束"))
        self.action4.setText(_translate("MainWindow", "保存测量结果"))
        self.action5.setText(_translate("MainWindow", "退出"))
        self.actionconnect.setText(_translate("MainWindow", "测试VNA连接状态"))
        self.actiondisconnect.setText(_translate("MainWindow", "断开连接"))
        self.actionhelp.setText(_translate("MainWindow", "帮助信息"))
        self.actionopen.setText(_translate("MainWindow", "打开测量结果"))
        self.action.setText(_translate("MainWindow", "继续"))

        # self.action_3.setText(_translate("MainWindow", "保存设置"))
